# Generated by Django 4.2 on 2023-05-18 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_wellness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ill', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='1', max_length=50)),
                ('garments', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='1', max_length=50)),
                ('wash', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='1', max_length=50)),
                ('jwelry', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='1', max_length=50)),
                ('hair', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='1', max_length=50)),
                ('food', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='1', max_length=50)),
                ('food_package', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hazard_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sh_wallnut', models.CharField(choices=[('B', 'Biological'), ('c', 'chemical'), ('p', 'pysical')], default='B', max_length=50)),
                ('Desc', models.CharField(default='1', max_length=50)),
                ('rc_shwallnut', models.CharField(choices=[('B', 'Biological'), ('c', 'chemical'), ('p', 'pysical')], default='B', max_length=50)),
                ('Desc1', models.CharField(default='1', max_length=50)),
                ('sorting', models.CharField(choices=[('B', 'Biological'), ('c', 'chemical'), ('p', 'pysical')], default='B', max_length=50)),
                ('Desc2', models.CharField(default='1', max_length=50)),
                ('shelling', models.CharField(choices=[('B', 'Biological'), ('c', 'chemical'), ('p', 'pysical')], default='B', max_length=50)),
                ('Desc3', models.CharField(default='1', max_length=50)),
                ('sizer', models.CharField(choices=[('B', 'Biological'), ('c', 'chemical'), ('p', 'pysical')], default='B', max_length=50)),
                ('Desc4', models.CharField(default='1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Metal2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp', models.CharField(max_length=50)),
                ('InsNo', models.CharField(max_length=50)),
                ('Loc', models.CharField(max_length=50)),
                ('Working', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=5)),
                ('Type', models.CharField(choices=[('F', 'Ferrous'), ('N', 'Non-Ferrous'), ('S', 'Stainless-Steel')], max_length=20)),
                ('Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Comments', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Metal_detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp', models.CharField(max_length=50)),
                ('InsNo', models.CharField(max_length=50)),
                ('Loc', models.CharField(max_length=50)),
                ('Working', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=5)),
                ('Type', models.CharField(choices=[('F', 'Ferrous'), ('N', 'Non-Ferrous'), ('S', 'Stainless-Steel')], max_length=20)),
                ('Comments', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(default='1', max_length=25)),
                ('Last_Name', models.CharField(default='1', max_length=25)),
                ('emailAdd', models.CharField(max_length=50)),
                ('phoneNo', models.IntegerField()),
                ('EmpId', models.CharField(max_length=8)),
                ('Password', models.CharField(max_length=25)),
            ],
        ),
    ]
