# Generated by Django 4.2 on 2023-04-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myForms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
