# Generated by Django 4.2 on 2023-05-18 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myForms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='metal_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp', models.CharField(max_length=50)),
                ('InsNo', models.CharField(max_length=50)),
                ('Loc', models.CharField(max_length=50)),
                ('Working', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=5)),
                ('Type', models.CharField(choices=[('F', 'Ferrous'), ('N', 'Non-Ferrous'), ('S', 'Stainless-Steel')], max_length=20)),
                ('Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Comments', models.CharField(max_length=200)),
            ],
        ),
     
    ]
