# Generated by Django 4.2 on 2023-05-18 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myForms', '0002_metal_d_delete_metal2'),
    ]

    

