# Generated by Django 4.2 on 2023-05-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myForms', '0003_delete_metal2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Metal2',
        ),
    ]
