# Generated by Django 4.2 on 2023-04-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myForms', '0003_form2_delete_test_alter_form1_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='form2',
            name='Desc1',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='form2',
            name='Desc2',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='form2',
            name='Desc3',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='form2',
            name='Desc4',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='form2',
            name='rc_shwallnut',
            field=models.CharField(choices=[('B', 'Biological'), ('c', 'chemical'), ('p', 'pysical')], default='B', max_length=50),
        ),
        migrations.AddField(
            model_name='form2',
            name='shelling',
            field=models.CharField(choices=[('B', 'Biological'), ('c', 'chemical'), ('p', 'pysical')], default='B', max_length=50),
        ),
        migrations.AddField(
            model_name='form2',
            name='sizer',
            field=models.CharField(choices=[('B', 'Biological'), ('c', 'chemical'), ('p', 'pysical')], default='B', max_length=50),
        ),
        migrations.AddField(
            model_name='form2',
            name='sorting',
            field=models.CharField(choices=[('B', 'Biological'), ('c', 'chemical'), ('p', 'pysical')], default='B', max_length=50),
        ),
        migrations.AlterField(
            model_name='form2',
            name='Desc',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='form2',
            name='sh_wallnut',
            field=models.CharField(choices=[('B', 'Biological'), ('c', 'chemical'), ('p', 'pysical')], default='B', max_length=50),
        ),
    ]
