# Generated by Django 4.2 on 2023-05-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myForms', '0004_delete_metal2'),
    ]

    operations = [
        migrations.CreateModel(
            name='metal2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp', models.CharField(max_length=50)),
            ],
        ),
    ]
