# Generated by Django 4.2 on 2023-04-07 22:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myForms', '0004_form2_desc1_form2_desc2_form2_desc3_form2_desc4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form2',
            name='Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
