# Generated by Django 4.2 on 2023-05-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myForms', '0005_metal2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='metal2',
        ),
    ]
