# Generated by Django 4.2 on 2023-04-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myForms', '0005_form2_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ill', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='1', max_length=50)),
                ('garments', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='1', max_length=50)),
                ('wash', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='1', max_length=50)),
                ('jwelry', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='1', max_length=50)),
                ('hair', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='1', max_length=50)),
                ('food', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='1', max_length=50)),
                ('food_package', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=25)),
                ('Last_Name', models.CharField(max_length=25)),
                ('emailAdd', models.CharField(max_length=50)),
                ('phoneNo', models.IntegerField(max_length=10)),
                ('EmpId', models.CharField(max_length=8)),
                ('Password', models.CharField(max_length=25)),
            ],
        ),
    ]
