# Generated by Django 4.2 on 2023-04-11 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myForms', '0006_checkin_usernew'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckIN',
            new_name='checkModel',
        ),
    ]
