# Generated by Django 4.2 on 2023-05-18 23:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myForms', '0006_delete_metal2'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazard_material',
            name='Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
