# Generated by Django 4.2 on 2023-04-25 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myForms', '0007_rename_checkin_checkmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernew',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='usernew',
            name='Last_Name',
        ),
    ]
