# Generated by Django 4.2 on 2023-05-18 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myForms', '0007_hazard_material_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hazard_material',
            old_name='Time',
            new_name='Times',
        ),
    ]
