# Generated by Django 4.2 on 2023-04-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myForms', '0008_remove_usernew_first_name_remove_usernew_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernew',
            name='First_Name',
            field=models.CharField(default='1', max_length=25),
        ),
        migrations.AddField(
            model_name='usernew',
            name='Last_Name',
            field=models.CharField(default='1', max_length=25),
        ),
    ]
