# Generated by Django 4.2 on 2023-04-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myForms', '0009_usernew_first_name_usernew_last_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='checkModel',
            new_name='Emp_wellness',
        ),
        migrations.RenameModel(
            old_name='form2',
            new_name='Hazard_material',
        ),
        migrations.RenameModel(
            old_name='form1',
            new_name='Metal_detection',
        ),
        migrations.AlterField(
            model_name='usernew',
            name='phoneNo',
            field=models.IntegerField(),
        ),
    ]
