# Generated by Django 4.2 on 2023-04-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myForms', '0013_alter_hazard_material_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard_material',
            name='Time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
