# Generated by Django 4.2 on 2023-04-28 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myForms', '0015_alter_hazard_material_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard_material',
            name='Time',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=50),
        ),
    ]
