# Generated by Django 4.2 on 2023-04-28 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myForms', '0017_alter_hazard_material_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard_material',
            name='Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
