# Generated by Django 4.2 on 2023-05-08 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myForms', '0018_alter_hazard_material_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazard_material',
            name='Time',
        ),
        migrations.RemoveField(
            model_name='metal_detection',
            name='Time',
        ),
    ]
