# Generated by Django 4.2 on 2023-05-16 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myForms', '0019_remove_hazard_material_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metal_detection',
            name='Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
