# Generated by Django 4.2 on 2023-05-16 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myForms', '0020_metal_detection_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazard_material',
            name='Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
